### ISSUE TITLE
Cas particulier - Critère 7.1

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/Rgaa_Website#59]
Les cas particuliers indiqués pour le critère 7.1 sont un doublon de ceux du critère 6.1
http://rgaa.tanaguru.com/rgaa4-criteres.html#crit-7-1
7.1
![image](https://user-images.githubusercontent.com/41478857/86482645-a6b3f180-bd52-11ea-9b13-f38051b4dd31.png)

6.1
![image](https://user-images.githubusercontent.com/41478857/86482681-bcc1b200-bd52-11ea-95df-e622ffdf4a3e.png)

**Comment by juliemoynat-tanaguru** [comment]
Non, c'est pas un doublon, c'est normal. cf. le RGAA officiel https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#contenu
Les tests concernés sont bien précisés et correspondent bien à chaque fois au bon critère.
