### ISSUE TITLE
Critère 11.5 - VF - niveau RGAA

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/Rgaa_Website#61]
Dans la version française, le critère 11.5 est indiqué comme étant A. Après vérification rapide sur le site de la DINUM, il semblerait que ça devrait être niveau AA.

**Comment by nmadeuf** [comment]
NB: idem pour le critère 11.7

**Comment by juliemoynat-tanaguru** [comment]
@nmadeuf, non, quand on filtre pour afficher les critères de niveau AA, ces critères n'apparaissent pas. Ils sont bien du niveau A.
